from pathlib import Path
import re
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
STYLE_HREF = "/assets/premium-icons.css?v=1.0.0"
STYLE_TAG = f'<link rel="stylesheet" href="{STYLE_HREF}"/>'

PAGES = {
    "index.html": "home",
    "start/index.html": "start",
    "about.html": "about",
    "experience.html": "experience",
    "projects.html": "projects",
    "insights/index.html": "insights",
    "contact.html": "contact",
    "evidence.html": "evidence",
    "privacy.html": "privacy",
    "terms.html": "terms",
    "faq.html": "faq",
    "case-studies/route-remapping-retention.html": "case-study",
    "case-studies/bold-loud-customer-development.html": "case-study",
    "case-studies/trade-activation-enugu.html": "case-study",
    "case-studies/abacha-festival-activation.html": "case-study",
    "insights/sales-reviews-end-with-route-decision.html": "insight-article",
    "insights/trade-activation-must-change-behaviour.html": "insight-article",
    "insights/follow-up-wins.html": "insight-article",
    "insights/availability-beats-intention.html": "insight-article",
    "insights/route-discipline.html": "insight-article",
    "growth-system.html": "growth-system",
    "retention-system.html": "retention-system",
    "insights/why-customers-leave.html": "insight-article",
    "insights/customer-retention-vs-loyalty.html": "insight-article",
    "tools/retention-health-check.html": "retention-health-check",
    "404.html": "404",
}

SEMANTIC = {
    "search": '<circle cx="11" cy="11" r="6.5"/><path d="m16 16 4.5 4.5"/>',
    "users": '<path d="M16 21v-2a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4v2"/><circle cx="9.5" cy="7.5" r="3.5"/><path d="M18 8a3 3 0 0 1 0 6M21 21v-2a4 4 0 0 0-3-3.87"/>',
    "route": '<circle cx="6" cy="18" r="2"/><circle cx="18" cy="6" r="2"/><path d="M8 18c6 0 2-10 8-10"/><path d="M10 6H5v5"/>',
    "repeat": '<path d="m17 2 4 4-4 4"/><path d="M3 11V9a3 3 0 0 1 3-3h15"/><path d="m7 22-4-4 4-4"/><path d="M21 13v2a3 3 0 0 1-3 3H3"/>',
    "trophy": '<path d="M8 21h8M12 17v4"/><path d="M7 4h10v4a5 5 0 0 1-10 0V4Z"/><path d="M7 6H4v1a4 4 0 0 0 4 4M17 6h3v1a4 4 0 0 1-4 4"/>',
    "chart": '<path d="M4 20V10M10 20V4M16 20v-7M22 20V8"/><path d="M3 20h20"/>',
    "eye": '<path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.5"/>',
    "filter": '<path d="M4 5h16l-6 7v6l-4 2v-8L4 5Z"/>',
    "arrow": '<path d="M5 19 19 5"/><path d="M10 5h9v9"/>',
    "shieldcheck": '<path d="M12 22s8-3 8-10V5l-8-3-8 3v7c0 7 8 10 8 10Z"/><path d="m9 12 2 2 4-5"/>',
    "target": '<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="m14 10 6-6"/>',
    "megaphone": '<path d="m3 11 14-6v14L3 13v-2Z"/><path d="M7 14v5a2 2 0 0 0 2 2h1v-5"/>',
    "globe": '<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a14 14 0 0 1 0 18M12 3a14 14 0 0 0 0 18"/>',
    "sale": '<path d="M5 7h14l-1 13H6L5 7Z"/><path d="M8 7a4 4 0 0 1 8 0"/><path d="m9 13 2 2 4-4"/>',
    "workflow": '<rect x="3" y="4" width="6" height="5" rx="1.5"/><rect x="15" y="15" width="6" height="5" rx="1.5"/><path d="M9 6.5h4a4 4 0 0 1 4 4v4.5M15 17.5h-4a4 4 0 0 1-4-4V9"/>',
    "heart": '<path d="M20.8 4.6a5.4 5.4 0 0 0-7.6 0L12 5.8l-1.2-1.2a5.4 5.4 0 1 0-7.6 7.6L12 21l8.8-8.8a5.4 5.4 0 0 0 0-7.6Z"/>',
    "clipboard": '<rect x="5" y="4" width="14" height="17" rx="2"/><path d="M9 4V2h6v2M9 10h6M9 14h6"/>',
    "card": '<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 10h18M7 15h4"/>',
    "network": '<circle cx="5" cy="12" r="2"/><circle cx="19" cy="5" r="2"/><circle cx="19" cy="19" r="2"/><path d="m7 11 10-5M7 13l10 5"/>',
    "question": '<circle cx="12" cy="12" r="9"/><path d="M9.5 9a2.7 2.7 0 1 1 4.4 2.1c-1.3 1-1.9 1.4-1.9 2.9M12 18h.01"/>',
    "diamond": '<path d="m12 3 8 7-8 11-8-11 8-7Z"/><path d="M4 10h16M8 6l4 4 4-4"/>',
    "bolt": '<path d="M13 2 5 14h7l-1 8 8-12h-7l1-8Z"/>',
    "message": '<path d="M21 15a4 4 0 0 1-4 4H8l-5 3 1.5-5A7 7 0 0 1 3 13V8a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4v7Z"/><path d="M8 10h8M8 14h5"/>',
    "gift": '<rect x="3" y="9" width="18" height="12" rx="2"/><path d="M12 9v12M3 13h18"/><path d="M12 9H8.5A2.5 2.5 0 1 1 11 6.5L12 9Zm0 0h3.5A2.5 2.5 0 1 0 13 6.5L12 9Z"/>',
    "support": '<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="3"/><path d="m5.6 5.6 4.3 4.3M14.1 14.1l4.3 4.3M18.4 5.6l-4.3 4.3M9.9 14.1l-4.3 4.3"/>',
    "spark": '<path d="m12 3 1.4 4.1L17.5 8.5l-4.1 1.4L12 14l-1.4-4.1-4.1-1.4 4.1-1.4L12 3Z"/><path d="m19 14 .8 2.2L22 17l-2.2.8L19 20l-.8-2.2L16 17l2.2-.8L19 14Z"/>',
    "compass": '<circle cx="12" cy="12" r="9"/><path d="m15.5 8.5-2.2 4.8-4.8 2.2 2.2-4.8 4.8-2.2Z"/>',
    "filecheck": '<path d="M6 2h8l4 4v16H6V2Z"/><path d="M14 2v5h5M9 14l2 2 4-4"/>',
    "download": '<path d="M12 3v12"/><path d="m7 10 5 5 5-5"/><path d="M5 21h14"/>',
    "mail": '<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/>',
    "check": '<circle cx="12" cy="12" r="9"/><path d="m8 12 2.5 2.5L16 9"/>',
}

BRAND = {
    "whatsapp": '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10" fill="#25D366"/><path fill="#fff" d="M8.1 6.9c-.3-.7-.6-.7-.9-.7h-.7c-.3 0-.7.1-1.1.5-.4.4-1.4 1.4-1.4 3.4s1.5 4 1.7 4.3c.2.3 2.9 4.6 7.2 6.3 3.6 1.4 4.3 1.1 5.1 1 .8-.1 2.6-1 2.9-2 .4-1 .4-1.9.3-2.1-.1-.2-.4-.3-.9-.5L15 14.6c-.4-.2-.8-.3-1.1.2-.3.5-1.3 1.6-1.6 2-.3.4-.6.4-1.1.1-.5-.2-2-.8-3.8-2.3-1.4-1.3-2.4-2.8-2.7-3.3-.3-.5 0-.8.2-1 .2-.2.5-.6.7-.9.2-.3.3-.5.4-.8.1-.3.1-.6 0-.8L8.1 6.9Z" transform="scale(.68) translate(5 3)"/></svg>',
    "telegram": '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10" fill="#229ED9"/><path fill="#fff" d="m17.8 7-2.1 10c-.2.7-.6.9-1.2.5l-3.2-2.4-1.5 1.5c-.2.2-.3.3-.7.3l.2-3.3 6-5.4c.3-.2-.1-.4-.4-.1l-7.4 4.7-3.2-1c-.7-.2-.7-.7.1-1l12.5-4.8c.6-.2 1.1.1.9 1Z"/></svg>',
    "linkedin": '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><rect x="2" y="2" width="20" height="20" rx="5" fill="#0A66C2"/><path fill="#fff" d="M7 9.5h2.6V18H7V9.5Zm1.3-4.2a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM11.1 9.5h2.5v1.2h.04c.35-.67 1.2-1.38 2.48-1.38 2.66 0 3.15 1.75 3.15 4.04V18h-2.62v-4.1c0-.98-.02-2.23-1.36-2.23-1.36 0-1.57 1.07-1.57 2.16V18h-2.62V9.5Z"/></svg>',
    "facebook": '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10" fill="#1877F2"/><path fill="#fff" d="M13.5 20v-7h2.35l.35-2.72h-2.7V8.54c0-.79.22-1.32 1.35-1.32h1.44V4.79c-.25-.03-1.1-.11-2.1-.11-2.08 0-3.5 1.27-3.5 3.6v2h-2.35V13h2.35v7h2.81Z"/></svg>',
    "instagram": '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><defs><linearGradient id="g" x1="2" y1="22" x2="22" y2="2"><stop stop-color="#FFDC80"/><stop offset=".35" stop-color="#F77737"/><stop offset=".68" stop-color="#E1306C"/><stop offset="1" stop-color="#833AB4"/></linearGradient></defs><rect x="2" y="2" width="20" height="20" rx="6" fill="url(#g)"/><circle cx="12" cy="12" r="4.1" fill="none" stroke="#fff" stroke-width="1.8"/><circle cx="17.4" cy="6.6" r="1.1" fill="#fff"/></svg>',
}

def semantic_svg(body):
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" '
        'fill="none" stroke="#174B36" stroke-width="1.85" '
        'stroke-linecap="round" stroke-linejoin="round">' + body + '</svg>'
    )

def url(svg):
    return 'url("data:image/svg+xml,' + quote(svg, safe='') + '")'

vars_css = ["  --pi-%s:%s;" % (name, url(semantic_svg(body))) for name, body in SEMANTIC.items()]
vars_css += ["  --pi-brand-%s:%s;" % (name, url(svg)) for name, svg in BRAND.items()]

CSS = "\n".join([
"/* Premium SVG icon system — lightweight, inline-vector, no external icon font. */",
":root{",
*vars_css,
"}",
"",
"/* Shared premium icon badge language */",
"[data-page=\"home\"] .choice-card::before,",
"[data-page=\"retention-system\"] #retention-start .choice-card::before,",
"[data-page=\"projects\"] .service::before,",
"[data-page=\"growth-system\"] .method-card::before,",
"[data-page=\"about\"] .card-grid .card::before{",
"  content:\"\";display:block;width:46px;height:46px;margin:0 0 18px;border-radius:15px;",
"  border:1px solid rgba(23,75,54,.10);background-color:rgba(23,75,54,.065);",
"  background-image:var(--pi-icon,var(--pi-spark));background-repeat:no-repeat;background-position:center;background-size:24px 24px;",
"  box-shadow:0 10px 24px rgba(21,49,37,.07),inset 0 1px 0 rgba(255,255,255,.82);",
"}",
"",
"/* Home: problem-first cards, proof and growth path */",
"[data-page=\"home\"] .choice-card[data-category=\"sales\"]{--pi-icon:var(--pi-sale)}",
"[data-page=\"home\"] .choice-card[data-category=\"retention\"]{--pi-icon:var(--pi-heart)}",
"[data-page=\"home\"] .choice-card[data-category=\"execution\"]{--pi-icon:var(--pi-route)}",
"[data-page=\"home\"] .metric,[data-page=\"experience\"] .metric,[data-page=\"retention-system\"] .signal-card,[data-page=\"retention-system\"] .retention-card,[data-page=\"evidence\"] .evidence-item{position:relative}",
"[data-page=\"home\"] .metric::before,[data-page=\"experience\"] .metric::before,[data-page=\"retention-system\"] .signal-card::before,[data-page=\"retention-system\"] .retention-card::before,[data-page=\"evidence\"] .evidence-item::before{",
"  content:\"\";position:absolute;top:15px;right:15px;width:34px;height:34px;border-radius:11px;",
"  border:1px solid rgba(23,75,54,.09);background-color:rgba(23,75,54,.055);",
"  background-image:var(--pi-icon,var(--pi-check));background-repeat:no-repeat;background-position:center;background-size:18px 18px;",
"}",
"[data-page=\"home\"] .metric:nth-child(1),[data-page=\"experience\"] .metric:nth-child(1){--pi-icon:var(--pi-repeat)}",
"[data-page=\"home\"] .metric:nth-child(2),[data-page=\"experience\"] .metric:nth-child(2){--pi-icon:var(--pi-trophy)}",
"[data-page=\"home\"] .metric:nth-child(3),[data-page=\"experience\"] .metric:nth-child(3){--pi-icon:var(--pi-chart)}",
"[data-page=\"home\"] .metric:nth-child(4){--pi-icon:var(--pi-users)}",
"[data-page=\"experience\"] .metric:nth-child(4){--pi-icon:var(--pi-chart)}",
"",
"[data-page=\"home\"] .growth-flow>div::before,[data-page=\"retention-system\"] .growth-flow>div::before,[data-page=\"about\"] .process-rail>div::before{",
"  content:\"\";display:block;width:38px;height:38px;margin:0 0 12px;border-radius:12px;border:1px solid rgba(23,75,54,.10);",
"  background-color:rgba(23,75,54,.06);background-image:var(--pi-icon,var(--pi-spark));background-repeat:no-repeat;background-position:center;background-size:20px 20px;",
"}",
"[data-page=\"home\"] .growth-flow>div:nth-child(1){--pi-icon:var(--pi-search)}",
"[data-page=\"home\"] .growth-flow>div:nth-child(2){--pi-icon:var(--pi-eye)}",
"[data-page=\"home\"] .growth-flow>div:nth-child(3){--pi-icon:var(--pi-target)}",
"[data-page=\"home\"] .growth-flow>div:nth-child(4){--pi-icon:var(--pi-bolt)}",
"[data-page=\"home\"] .growth-flow>div:nth-child(5){--pi-icon:var(--pi-chart)}",
"[data-page=\"home\"] .growth-flow>div:nth-child(6){--pi-icon:var(--pi-repeat)}",
"",
"/* Approach */",
"[data-page=\"about\"] .process-rail>div:nth-child(1){--pi-icon:var(--pi-eye)}",
"[data-page=\"about\"] .process-rail>div:nth-child(2){--pi-icon:var(--pi-filter)}",
"[data-page=\"about\"] .process-rail>div:nth-child(3){--pi-icon:var(--pi-arrow)}",
"[data-page=\"about\"] .process-rail>div:nth-child(4){--pi-icon:var(--pi-shieldcheck)}",
"[data-page=\"about\"] .card-grid .card:nth-child(1){--pi-icon:var(--pi-search)}",
"[data-page=\"about\"] .card-grid .card:nth-child(2){--pi-icon:var(--pi-target)}",
"[data-page=\"about\"] .card-grid .card:nth-child(3){--pi-icon:var(--pi-chart)}",
"",
"/* Solutions: six-stage system tabs */",
"[data-page=\"projects\"] .growth-diagram button::before{",
"  content:\"\";display:inline-block;width:18px;height:18px;margin-right:8px;vertical-align:-4px;",
"  background-image:var(--pi-icon,var(--pi-spark));background-repeat:no-repeat;background-position:center;background-size:18px 18px;",
"}",
"[data-page=\"projects\"] [data-growth-tab=\"research\"]{--pi-icon:var(--pi-search)}",
"[data-page=\"projects\"] [data-growth-tab=\"plan\"]{--pi-icon:var(--pi-clipboard)}",
"[data-page=\"projects\"] [data-growth-tab=\"reach\"]{--pi-icon:var(--pi-megaphone)}",
"[data-page=\"projects\"] [data-growth-tab=\"sell\"]{--pi-icon:var(--pi-sale)}",
"[data-page=\"projects\"] [data-growth-tab=\"retain\"]{--pi-icon:var(--pi-heart)}",
"[data-page=\"projects\"] [data-growth-tab=\"improve\"]{--pi-icon:var(--pi-repeat)}",
"[data-page=\"projects\"] #strategy .service:nth-child(1){--pi-icon:var(--pi-search)}",
"[data-page=\"projects\"] #strategy .service:nth-child(2){--pi-icon:var(--pi-users)}",
"[data-page=\"projects\"] #strategy .service:nth-child(3){--pi-icon:var(--pi-clipboard)}",
"[data-page=\"projects\"] #campaigns .service:nth-child(1){--pi-icon:var(--pi-arrow)}",
"[data-page=\"projects\"] #campaigns .service:nth-child(2){--pi-icon:var(--pi-megaphone)}",
"[data-page=\"projects\"] #campaigns .service:nth-child(3){--pi-icon:var(--pi-network)}",
"[data-page=\"projects\"] #digital .service:nth-child(1){--pi-icon:var(--pi-globe)}",
"[data-page=\"projects\"] #digital .service:nth-child(2){--pi-icon:var(--pi-message)}",
"[data-page=\"projects\"] #digital .service:nth-child(3){--pi-icon:var(--pi-workflow)}",
"[data-page=\"projects\"] #sales .service:nth-child(1){--pi-icon:var(--pi-question)}",
"[data-page=\"projects\"] #sales .service:nth-child(2){--pi-icon:var(--pi-diamond)}",
"[data-page=\"projects\"] #sales .service:nth-child(3){--pi-icon:var(--pi-check)}",
"[data-page=\"projects\"] #execution .service:nth-child(1){--pi-icon:var(--pi-users)}",
"[data-page=\"projects\"] #execution .service:nth-child(2){--pi-icon:var(--pi-route)}",
"[data-page=\"projects\"] #execution .service:nth-child(3){--pi-icon:var(--pi-bolt)}",
"[data-page=\"projects\"] #retention .service:nth-child(1){--pi-icon:var(--pi-support)}",
"[data-page=\"projects\"] #retention .service:nth-child(2){--pi-icon:var(--pi-route)}",
"[data-page=\"projects\"] #retention .service:nth-child(3){--pi-icon:var(--pi-heart)}",
"",
"/* Growth System: semantic card icons by step */",
"[data-page=\"growth-system\"] main>section:nth-of-type(2) .method-card:nth-child(1){--pi-icon:var(--pi-search)}",
"[data-page=\"growth-system\"] main>section:nth-of-type(2) .method-card:nth-child(2){--pi-icon:var(--pi-users)}",
"[data-page=\"growth-system\"] main>section:nth-of-type(2) .method-card:nth-child(3){--pi-icon:var(--pi-target)}",
"[data-page=\"growth-system\"] main>section:nth-of-type(3) .method-card:nth-child(1){--pi-icon:var(--pi-target)}",
"[data-page=\"growth-system\"] main>section:nth-of-type(3) .method-card:nth-child(2){--pi-icon:var(--pi-card)}",
"[data-page=\"growth-system\"] main>section:nth-of-type(3) .method-card:nth-child(3){--pi-icon:var(--pi-route)}",
"[data-page=\"growth-system\"] main>section:nth-of-type(4) .method-card:nth-child(1){--pi-icon:var(--pi-arrow)}",
"[data-page=\"growth-system\"] main>section:nth-of-type(4) .method-card:nth-child(2){--pi-icon:var(--pi-megaphone)}",
"[data-page=\"growth-system\"] main>section:nth-of-type(4) .method-card:nth-child(3){--pi-icon:var(--pi-network)}",
"[data-page=\"growth-system\"] main>section:nth-of-type(7) .method-card:nth-child(1){--pi-icon:var(--pi-users)}",
"[data-page=\"growth-system\"] main>section:nth-of-type(7) .method-card:nth-child(2){--pi-icon:var(--pi-target)}",
"[data-page=\"growth-system\"] main>section:nth-of-type(7) .method-card:nth-child(3){--pi-icon:var(--pi-route)}",
"[data-page=\"growth-system\"] main>section:nth-of-type(7) .method-card:nth-child(4){--pi-icon:var(--pi-diamond)}",
"[data-page=\"growth-system\"] main>section:nth-of-type(7) .method-card:nth-child(5){--pi-icon:var(--pi-bolt)}",
"[data-page=\"growth-system\"] main>section:nth-of-type(7) .method-card:nth-child(6){--pi-icon:var(--pi-workflow)}",
"[data-page=\"growth-system\"] main>section:nth-of-type(8) .method-card:nth-child(1){--pi-icon:var(--pi-support)}",
"[data-page=\"growth-system\"] main>section:nth-of-type(8) .method-card:nth-child(2){--pi-icon:var(--pi-route)}",
"[data-page=\"growth-system\"] main>section:nth-of-type(8) .method-card:nth-child(3){--pi-icon:var(--pi-spark)}",
"[data-page=\"growth-system\"] main>section:nth-of-type(8) .method-card:nth-child(4){--pi-icon:var(--pi-card)}",
"[data-page=\"growth-system\"] main>section:nth-of-type(8) .method-card:nth-child(5){--pi-icon:var(--pi-gift)}",
"[data-page=\"growth-system\"] main>section:nth-of-type(8) .method-card:nth-child(6){--pi-icon:var(--pi-message)}",
"[data-page=\"growth-system\"] .sales-method>span::before{content:\"\";display:block;width:22px;height:22px;margin:0 auto 7px;background-image:var(--pi-icon,var(--pi-spark));background-repeat:no-repeat;background-position:center;background-size:22px 22px}",
"[data-page=\"growth-system\"] .sales-method:nth-child(1){--pi-icon:var(--pi-question)}",
"[data-page=\"growth-system\"] .sales-method:nth-child(2){--pi-icon:var(--pi-diamond)}",
"[data-page=\"growth-system\"] .sales-method:nth-child(3){--pi-icon:var(--pi-compass)}",
"[data-page=\"growth-system\"] .sales-method:nth-child(4){--pi-icon:var(--pi-spark)}",
"[data-page=\"growth-system\"] .sales-method:nth-child(5){--pi-icon:var(--pi-check)}",
"",
"/* Retention System */",
"[data-page=\"retention-system\"] #retention-start .choice-card:nth-child(1){--pi-icon:var(--pi-search)}",
"[data-page=\"retention-system\"] #retention-start .choice-card:nth-child(2){--pi-icon:var(--pi-compass)}",
"[data-page=\"retention-system\"] #retention-start .choice-card:nth-child(3){--pi-icon:var(--pi-check)}",
"[data-page=\"retention-system\"] .retention-signals .signal-card:nth-child(1){--pi-icon:var(--pi-repeat)}",
"[data-page=\"retention-system\"] .retention-signals .signal-card:nth-child(2){--pi-icon:var(--pi-heart)}",
"[data-page=\"retention-system\"] .retention-signals .signal-card:nth-child(3){--pi-icon:var(--pi-card)}",
"[data-page=\"retention-system\"] .retention-signals .signal-card:nth-child(4){--pi-icon:var(--pi-gift)}",
"[data-page=\"retention-system\"] .retention-card:nth-child(1){--pi-icon:var(--pi-support)}",
"[data-page=\"retention-system\"] .retention-card:nth-child(2){--pi-icon:var(--pi-heart)}",
"[data-page=\"retention-system\"] .retention-card:nth-child(3){--pi-icon:var(--pi-network)}",
"[data-page=\"retention-system\"] .retention-card:nth-child(4){--pi-icon:var(--pi-spark)}",
"[data-page=\"retention-system\"] .retention-card:nth-child(5){--pi-icon:var(--pi-card)}",
"[data-page=\"retention-system\"] .retention-card:nth-child(6){--pi-icon:var(--pi-gift)}",
"[data-page=\"retention-system\"] .retention-card:nth-child(7){--pi-icon:var(--pi-message)}",
"[data-page=\"retention-system\"] .retention-flow>div:nth-child(1){--pi-icon:var(--pi-search)}",
"[data-page=\"retention-system\"] .retention-flow>div:nth-child(2){--pi-icon:var(--pi-support)}",
"[data-page=\"retention-system\"] .retention-flow>div:nth-child(3){--pi-icon:var(--pi-clipboard)}",
"[data-page=\"retention-system\"] .retention-flow>div:nth-child(4){--pi-icon:var(--pi-shieldcheck)}",
"[data-page=\"retention-system\"] .retention-flow>div:nth-child(5){--pi-icon:var(--pi-gift)}",
"[data-page=\"retention-system\"] .retention-flow>div:nth-child(6){--pi-icon:var(--pi-chart)}",
"[data-page=\"retention-system\"] .scan-card-grid .scan-card{position:relative;padding-top:58px}",
"[data-page=\"retention-system\"] .scan-card-grid .scan-card::before{content:\"\";position:absolute;top:18px;left:18px;width:28px;height:28px;background-image:var(--pi-icon,var(--pi-chart));background-repeat:no-repeat;background-position:center;background-size:22px 22px}",
"[data-page=\"retention-system\"] .scan-card-grid .scan-card:nth-child(1){--pi-icon:var(--pi-repeat)}",
"[data-page=\"retention-system\"] .scan-card-grid .scan-card:nth-child(2){--pi-icon:var(--pi-route)}",
"[data-page=\"retention-system\"] .scan-card-grid .scan-card:nth-child(3){--pi-icon:var(--pi-support)}",
"[data-page=\"retention-system\"] .scan-card-grid .scan-card:nth-child(4){--pi-icon:var(--pi-chart)}",
"",
"/* Insights */",
"[data-page=\"insights\"] .featured-insight{position:relative;padding-right:58px}",
"[data-page=\"insights\"] .featured-insight::before{content:\"\";position:absolute;top:20px;right:20px;width:34px;height:34px;border-radius:11px;background-color:rgba(23,75,54,.06);background-image:var(--pi-filecheck);background-repeat:no-repeat;background-position:center;background-size:19px 19px}",
"[data-page=\"insights\"] .insight-search>span::before{content:\"\";display:inline-block;width:15px;height:15px;margin-right:6px;vertical-align:-2px;background-image:var(--pi-search);background-size:contain;background-repeat:no-repeat}",
"[data-page=\"insights\"] .insight-filter::before{content:\"\";display:inline-block;width:13px;height:13px;margin-right:5px;vertical-align:-2px;background-image:var(--pi-icon,var(--pi-filter));background-size:contain;background-repeat:no-repeat}",
"[data-page=\"insights\"] .insight-filter[data-insight-filter=\"sales\"]{--pi-icon:var(--pi-sale)}",
"[data-page=\"insights\"] .insight-filter[data-insight-filter=\"customers\"]{--pi-icon:var(--pi-users)}",
"[data-page=\"insights\"] .insight-filter[data-insight-filter=\"execution\"]{--pi-icon:var(--pi-bolt)}",
"[data-page=\"insights\"] .insight-filter[data-insight-filter=\"routes\"]{--pi-icon:var(--pi-route)}",
"[data-page=\"insights\"] .article-row{position:relative;padding-right:42px}",
"[data-page=\"insights\"] .article-row::after{content:\"\";position:absolute;right:14px;top:50%;width:16px;height:16px;transform:translateY(-50%);background-image:var(--pi-arrow);background-size:contain;background-repeat:no-repeat;opacity:.55;transition:transform .2s ease,opacity .2s ease}",
"[data-page=\"insights\"] .article-row:hover::after{transform:translate(2px,-2px);opacity:.9}",
"",
"/* Evidence and verification */",
"[data-page=\"evidence\"] .evidence-item#retention{--pi-icon:var(--pi-repeat)}",
"[data-page=\"evidence\"] .evidence-item#tenure{--pi-icon:var(--pi-chart)}",
"[data-page=\"evidence\"] .evidence-item#ranking{--pi-icon:var(--pi-trophy)}",
"[data-page=\"evidence\"] .evidence-item#recognition{--pi-icon:var(--pi-shieldcheck)}",
"[data-page=\"evidence\"] .evidence-item#festival{--pi-icon:var(--pi-users)}",
"[data-page=\"evidence\"] .evidence-item#creator{--pi-icon:var(--pi-chart)}",
"[data-page=\"evidence\"] .evidence-item#facebook-audience{--pi-icon:var(--pi-users)}",
"[data-page=\"evidence\"] .evidence-item#linkedin-recommendation{--pi-icon:var(--pi-shieldcheck)}",
"[data-page=\"evidence\"] a[download]::before{content:\"\";display:inline-block;width:16px;height:16px;margin-right:8px;vertical-align:-3px;background-image:var(--pi-download);background-size:contain;background-repeat:no-repeat}",
"[data-page=\"evidence\"] .actions a[href*=\"linkedin.com\"]::before,[data-page=\"home\"] .recommendation-meta a[href*=\"linkedin.com\"]::before,[data-page=\"experience\"] .recommendation-meta a[href*=\"linkedin.com\"]::before{content:\"\";display:inline-block;width:16px;height:16px;margin-right:7px;vertical-align:-3px;background-image:var(--pi-brand-linkedin);background-size:contain;background-repeat:no-repeat}",
"[data-page=\"home\"] .source-badge::before,[data-page=\"experience\"] .source-badge::before{content:\"\";display:inline-block;width:14px;height:14px;margin-right:5px;vertical-align:-2px;background-image:var(--pi-shieldcheck);background-size:contain;background-repeat:no-repeat}",
"",
"/* Retention health check */",
"[data-page=\"retention-health-check\"] .health-question legend::before{content:\"\";display:inline-block;width:22px;height:22px;margin-right:9px;vertical-align:-5px;background-image:var(--pi-icon,var(--pi-check));background-size:contain;background-repeat:no-repeat}",
"[data-page=\"retention-health-check\"] .health-question:nth-of-type(1){--pi-icon:var(--pi-repeat)}",
"[data-page=\"retention-health-check\"] .health-question:nth-of-type(2){--pi-icon:var(--pi-support)}",
"[data-page=\"retention-health-check\"] .health-question:nth-of-type(3){--pi-icon:var(--pi-eye)}",
"[data-page=\"retention-health-check\"] .health-question:nth-of-type(4){--pi-icon:var(--pi-message)}",
"[data-page=\"retention-health-check\"] .health-question:nth-of-type(5){--pi-icon:var(--pi-sale)}",
"[data-page=\"retention-health-check\"] .health-result-score::before{content:\"\";display:inline-block;width:18px;height:18px;margin-right:7px;vertical-align:-3px;background-image:var(--pi-chart);background-size:contain;background-repeat:no-repeat}",
"",
"/* Start page: three immediate problem routes */",
"[data-page=\"start\"] .start-problem-links a{display:inline-flex;align-items:center;gap:8px}",
"[data-page=\"start\"] .start-problem-links a::before{content:\"\";width:18px;height:18px;flex:0 0 18px;background-image:var(--pi-icon,var(--pi-arrow));background-size:contain;background-repeat:no-repeat;background-position:center}",
"[data-page=\"start\"] .start-problem-links li:nth-child(1){--pi-icon:var(--pi-sale)}",
"[data-page=\"start\"] .start-problem-links li:nth-child(2){--pi-icon:var(--pi-heart)}",
"[data-page=\"start\"] .start-problem-links li:nth-child(3){--pi-icon:var(--pi-route)}",
"",
"/* 404: one useful wayfinding symbol, no decorative clutter */",
"[data-page=\"404\"] h1::before{content:\"\";display:block;width:48px;height:48px;margin:0 0 18px;border-radius:15px;border:1px solid rgba(23,75,54,.1);background-color:rgba(23,75,54,.06);background-image:var(--pi-compass);background-position:center;background-repeat:no-repeat;background-size:25px 25px}",
"",
"/* Global social footer: official brand marks, small and consistent. */",
".footer-links a{display:inline-flex;align-items:center;gap:6px}",
".footer-links a[href*=\"wa.me\"]::before,.footer-links a[href*=\"t.me\"]::before,.footer-links a[href*=\"instagram.com\"]::before,.footer-links a[href*=\"linkedin.com\"]::before,.footer-links a[href*=\"facebook.com\"]::before{content:\"\";width:16px;height:16px;flex:0 0 16px;background-position:center;background-repeat:no-repeat;background-size:contain}",
".footer-links a[href*=\"wa.me\"]::before{background-image:var(--pi-brand-whatsapp)}",
".footer-links a[href*=\"t.me\"]::before{background-image:var(--pi-brand-telegram)}",
".footer-links a[href*=\"instagram.com\"]::before{background-image:var(--pi-brand-instagram)}",
".footer-links a[href*=\"linkedin.com\"]::before{background-image:var(--pi-brand-linkedin)}",
".footer-links a[href*=\"facebook.com\"]::before{background-image:var(--pi-brand-facebook)}",
"",
"@media (max-width:620px){",
"  [data-page=\"home\"] .choice-card::before,[data-page=\"retention-system\"] #retention-start .choice-card::before,[data-page=\"projects\"] .service::before,[data-page=\"growth-system\"] .method-card::before,[data-page=\"about\"] .card-grid .card::before{width:42px;height:42px;border-radius:13px;background-size:22px 22px;margin-bottom:14px}",
"  [data-page=\"home\"] .metric::before,[data-page=\"experience\"] .metric::before,[data-page=\"retention-system\"] .signal-card::before,[data-page=\"retention-system\"] .retention-card::before,[data-page=\"evidence\"] .evidence-item::before{width:30px;height:30px;top:12px;right:12px;background-size:16px 16px}",
"}",
"@media (prefers-reduced-motion:reduce){[data-page=\"insights\"] .article-row::after{transition:none}}",
]) + "\n"

(ROOT / "assets" / "premium-icons.css").write_text(CSS, encoding="utf-8")

for rel, page_id in PAGES.items():
    path = ROOT / rel
    if not path.exists():
        raise SystemExit(f"Missing expected page: {rel}")
    text = path.read_text(encoding="utf-8")
    if STYLE_HREF not in text:
        if "</head>" not in text:
            raise SystemExit(f"No </head> in {rel}")
        text = text.replace("</head>", STYLE_TAG + "\n</head>", 1)

    body_match = re.search(r"<body\b([^>]*)>", text, flags=re.I)
    if not body_match:
        raise SystemExit(f"No <body> in {rel}")
    body_tag = body_match.group(0)
    if "data-page=" not in body_tag:
        attrs = body_match.group(1)
        text = text[:body_match.start()] + f'<body data-page="{page_id}"{attrs}>' + text[body_match.end():]

    path.write_text(text, encoding="utf-8")

sitemap = ROOT / "sitemap.xml"
sitemap_text = sitemap.read_text(encoding="utf-8")
sitemap_text = re.sub(r"<lastmod>\d{4}-\d{2}-\d{2}</lastmod>", "<lastmod>2026-09-10</lastmod>", sitemap_text)
sitemap.write_text(sitemap_text, encoding="utf-8")

for cleanup in [
    ROOT / ".github" / "workflows" / "premium-icon-rollout.yml",
    ROOT / "scripts" / "apply_premium_icons.py",
]:
    if cleanup.exists():
        cleanup.unlink()
